name: ht_countries_client
description: A Dart client interface package for managing news countries.
repository: https://github.com/headlines-toolkit/ht-countries-client
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  equatable: ^2.0.7
  uuid: ^4.4.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
